//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#include<iostream>
using namespace std;
int main(){
    int firstTerm = 0;
    int secondTerm = 1;
    int sum = 0, finalSum = 0;
    while(sum<=4000000){              // Sequence do not exceed 4 million 
        sum = firstTerm + secondTerm;
        firstTerm = secondTerm;
        secondTerm = sum;
        if(sum % 2 ==0){     //adding only the even number in the series 
            finalSum +=sum; 
        }
    }
    cout<<finalSum;
}
//output -  4613732 
